@startuml

title
 <b>Forget Password Page</b>
end title

actor User
participant "LoginPage" as A

autonumber

User -> ForgetPasswordPage: request page
ForgetPasswordPage --> User : get ForgotPassword page
loop until submit or cancel
User -> ForgetPasswordPage : insert data into fields
ForgetPasswordPage -> ForgetPasswordController : update the ts model
ForgetPasswordController --> ForgetPasswordPage : get inserted data
ForgetPasswordPage --> User : view inserted data 
end
User -> ForgetPasswordPage : submit all the inserted data
ForgetPasswordPage -> ForgetPasswordController: onInit()
ForgetPasswordController -> HttpService : save()
HttpService -> REST_Backend : POST: /forgot
REST_Backend --> REST_Backend : validate inputs
alt HttpStatus other then 200
    REST_Backend --> HttpService: invalid inputs
    HttpService --> ForgetPasswordController: throw error message
    ForgetPasswordController --> ForgetPasswordPage: fill the error message
    ForgetPasswordPage --> User: get the error message
end
REST_Backend --> HttpService : valid inputs / send email with random password 
HttpService --> A : redirect to Login Page
A --> User: get requested page
User -> A: insert new data

@enduml