@startuml

autonumber

WebCient -> UserController: HTTP: PUT /user/{id}/password
UserController -> UserService: changePassword: UserPasswordDto
UserService ->UserDao: changePassword: UserPassword
UserDao -> DB: SQL query

DB--> UserDao: Query Response

alt password could not be changed
    
    UserDao --> UserService: return false: password can not be changed
    UserService --> UserController: null reference 
    UserController --> WebCient: HTTP code 204
end

alt password changed
    UserDao --> UserService: the UserPassword
    UserService -> UserService: convertToDto()
    UserService --> UserController: the UserPasswordDto instance 
    UserController --> WebCient: HTTP code 200: the UserPasswordDto as JSON 
end

@enduml