@startuml

autonumber

WebCient -> PasswordController: HTTP: POST /forgot
PasswordController -> UserService: changeNewPassword: UserNewPasswordDto
UserService ->UserDao: changeNewPassword: UserNewPassword
UserDao -> DB: SQL query

DB--> UserDao: Query Response

alt user was not found
    UserDao --> UserService: null reference
    UserService --> UserController: null reference 
    UserController --> WebCient: HTTP code 204: content not found
end


alt password could not be changed
    
    UserDao --> UserService: return false: password can not be changed
    UserService --> PasswordController: null reference 
    PasswordController --> WebCient: HTTP code 204
end

alt password changed
    UserDao --> UserService: the UserNewPassword
    UserService -> UserService: convertToDto()
    UserService --> PasswordController: the UserNewPasswordDto instance 
    PasswordController --> WebCient: HTTP code 200: the UserNewPasswordDto as JSON 
end

@enduml